export const types = {
    AUTHENTICATE: "AUTHENTICATE",
    INITIALIZE: "INITIALIZE",
    SIGNUP_ASYNC: "SIGNUP_ASYNC",
    LOGIN_ASYNC: "LOGIN_ASYNC",
    AUTHENTICATE_ASYNC: "AUTHENTICATE_ASYNC",
    INITIALIZE_ASYNC: "INITIALIZE_ASYNC",
}
